
SELECT * FROM PAGING;

-- 전체 삭제
DELETE FROM PAGING;

-- 입력
INSERT INTO PAGING(TITLE, REGDATE)
VALUES('234523452', SYSDATE);

-- 글 개수
SELECT COUNT(*) FROM PAGING;

-- PAGING 글 조회

SELECT TITLE, REGDATE
FROM(SELECT ROWNUM RN, TITLE, REGDATE	
		FROM(SELECT TITLE, REGDATE
			 FROM PAGING
	 		ORDER BY REGDATE DESC)
	 )
WHERE RN BETWEEN 1 AND 10;

CREATE VIEW JOINTABLE AS SELECT ROWNUM RN, TITLE, REGDATE	
		FROM(SELECT TITLE, REGDATE
			 FROM PAGING
	 		ORDER BY REGDATE DESC)

SELECT TITLE, REGDATE
	FROM JOINTABLE
	WHERE RN BETWEEN 1 AND 10;
	
SELECT TITLE, REGDATE 
FROM(SELECT TITLE, REGDATE, ROW_NUMBER() OVER(ORDER BY REGDATE DESC) AS RN 
FROM PAGING)
WHERE RN BETWEEN 1 AND 10;